package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"github.com/tucosaurus/coke/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Devotion)
// DB Table: Plural (devotions)
// Resource: Plural (Devotions)
// Path: Plural (/devotions)
// View Template Folder: Plural (/templates/devotions/)

// DevotionsResource is the resource for the Devotion model
type DevotionsResource struct {
	buffalo.Resource
}

// List gets all Devotions. This function is mapped to the path
// GET /devotions
func (v DevotionsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	devotions := &models.Devotions{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Devotions from the DB
	if err := q.All(devotions); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, devotions))
}

// Show gets the data for one Devotion. This function is mapped to
// the path GET /devotions/{devotion_id}
func (v DevotionsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Devotion
	devotion := &models.Devotion{}

	// To find the Devotion the parameter devotion_id is used.
	if err := tx.Find(devotion, c.Param("devotion_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, devotion))
}

// New renders the form for creating a new Devotion.
// This function is mapped to the path GET /devotions/new
func (v DevotionsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Devotion{}))
}

// Create adds a Devotion to the DB. This function is mapped to the
// path POST /devotions
func (v DevotionsResource) Create(c buffalo.Context) error {
	// Allocate an empty Devotion
	devotion := &models.Devotion{}

	// Bind devotion to the html form elements
	if err := c.Bind(devotion); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(devotion)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, devotion))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Devotion was created successfully")

	// and redirect to the devotions index page
	return c.Render(201, r.Auto(c, devotion))
}

// Edit renders a edit form for a Devotion. This function is
// mapped to the path GET /devotions/{devotion_id}/edit
func (v DevotionsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Devotion
	devotion := &models.Devotion{}

	if err := tx.Find(devotion, c.Param("devotion_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, devotion))
}

// Update changes a Devotion in the DB. This function is mapped to
// the path PUT /devotions/{devotion_id}
func (v DevotionsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Devotion
	devotion := &models.Devotion{}

	if err := tx.Find(devotion, c.Param("devotion_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Devotion to the html form elements
	if err := c.Bind(devotion); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(devotion)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, devotion))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Devotion was updated successfully")

	// and redirect to the devotions index page
	return c.Render(200, r.Auto(c, devotion))
}

// Destroy deletes a Devotion from the DB. This function is mapped
// to the path DELETE /devotions/{devotion_id}
func (v DevotionsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Devotion
	devotion := &models.Devotion{}

	// To find the Devotion the parameter devotion_id is used.
	if err := tx.Find(devotion, c.Param("devotion_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(devotion); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Devotion was destroyed successfully")

	// Redirect to the devotions index page
	return c.Render(200, r.Auto(c, devotion))
}
